### ISSUE TITLE
Multiple issues including mak/

### ISSUE THREAD

**Issue by iajzenszmi** [hpyproject/hpy#316]
make
python3 setup.py build_ext -if
Traceback (most recent call last):
  File "/home/ian/hpy/hpy/setup.py", line 5, in <module>
    from setuptools import setup, Extension
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 38, in <module>
    from setuptools import windows_support
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_ctypes'

**Comment by pmp-p** [comment]
hi, you need libffi-dev for building CPython 3.11

**Comment by mattip** [comment]
Closing. The failure to import `_ctypes` is not specific to hpy, rather a problem with your build of python.
